config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resource :registrations, only: [:new, :create] do
    collection do
      get :confirm
      get :generate
    end
  end
  resource :sessions, only: [:new, :create, :destroy] do
    get '/', action: :create
    get '/token', as: :token, action: :token
  end

  namespace :api do
    get '/', to: 'api/api#root'

    resources :invoices do
      member do
        get :send_email
      end
    end

    match '*unmatched', to: 'api/api#not_found', via: :all
  end

  namespace :internal do
    resources :invoices
  end

  root 'application#root'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  include Emailable

  belongs_to :user

  validates :user_id, :number, :date, :company, :billing_for, :total, :emails, presence: true
  validate :validate_emails

  def splitted_emails
    emails.to_s.split(/[\r\n]+/)
  end

  private

  def validate_emails
    if splitted_emails.any? { |email| !EMAIL_FORMAT.match?(email) }
      errors.add(:emails, 'There\'s an invalid email')
    end
  end
end

app/controllers/api/invoices_controller.rb
module API
  class InvoicesController < APIController
    def index
      @invoices = InvoiceManager::ListInvoice.call(current_user, params[:filter]).payload

      render template: 'api/invoices/index.json.jbuilder'
    end

    def show
      response = InvoiceManager::FindInvoice.call(current_user, params[:id])

      if response.status
        @invoice = response.payload

        render template: 'api/invoices/show.json.jbuilder'
      else
        render json: { error: response.message }, status: :not_found
      end
    end

    def create
      response = InvoiceManager::CreateInvoice.call(current_user, invoice_params)

      if response.status
        @invoice = response.payload

        render template: 'api/invoices/show.json.jbuilder'
      else
        render json: { errors: response.error }, status: :unprocessable_entity
      end
    end

    def update
      response = InvoiceManager::UpdateInvoice.call(current_user, params[:id], invoice_params)

      if response.status
        @invoice = response.payload

        render template: 'api/invoices/show.json.jbuilder'
      elsif response.error
        render json: { errors: response.error }, status: :unprocessable_entity
      else
        render json: { error: response.message }, status: :not_found
      end
    end

    def send_email
      response = InvoiceManager::FindInvoice.call(current_user, params[:id])

      if response.status
        @invoice = response.payload
        @invoice.assign_attributes(invoice_params)
        @invoice.valid?

        if @invoice.errors[:emails].any?
          render json: { errors: { emails: @invoice.errors[:emails] } }, status: :bad_request
        else
          InvoiceManager::SendInvoice.call(response.payload, @invoice.splitted_emails)

          render json: {}, status: :accepted
        end
      else
        render json: { error: response.message }, status: :not_found
      end
    end

    private

    def invoice_params
      params.require(:invoice).permit(:number, :date, :company, :billing_for, :total, :emails)
    end
  end
end

app/controllers/internal/internal_controller.rb
module Internal
  class InternalController < ApplicationController
    prepend_before_action :authenticate!
  end
end

app/controllers/internal/invoices_controller.rb
module Internal
  class InvoicesController < InternalController
    def index
      @invoices = InvoiceManager::ListInvoice.call(current_user, params[:filter]).payload
    end

    def show
      response = InvoiceManager::FindInvoice.call(current_user, params[:id])

      if response.status
        @invoice = response.payload

        respond_to do |format|
          format.html { render :show }
          format.pdf do
            render pdf: 'invoice.pdf', layout: 'application.pdf.erb'
          end
        end

      else
        redirect_to internal_invoices_path, alert: response.message
      end
    end

    def new
      @invoice = Invoice.new
    end

    def edit
      response = InvoiceManager::FindInvoice.call(current_user, params[:id])

      if response.status
        @invoice = response.payload
      else
        redirect_to internal_invoices_path, alert: response.message
      end
    end

    def create
      response = InvoiceManager::CreateInvoice.call(current_user, invoice_params)

      if response.status
        redirect_to internal_invoice_path(response.payload), notice: response.message
      else
        @invoice = response.payload

        render :new, status: :unprocessable_entity
      end
    end

    def update
      response = InvoiceManager::UpdateInvoice.call(current_user, params[:id], invoice_params)

      if response.status
        redirect_to internal_invoice_path(response.payload), notice: response.message
      elsif response.payload
        @invoice = response.payload

        render :edit, status: :unprocessable_entity
      else
        redirect_to internal_invoices_path, alert: response.message
      end
    end

    def destroy
      response = InvoiceManager::DeleteInvoice.call(current_user, params[:id])

      key = response.status ? :notice : :alert

      redirect_to internal_invoices_path, key => response.message
    end

    private

    def invoice_params
      params.require(:invoice).permit(:id, :number, :date, :company, :billing_for, :total, :emails)
    end
  end
end

app/views/internal/invoices/_filters.html.erb
<%= form_with(scope: :filter, url: internal_invoices_path, method: :get, local: true, class: 'row g-3') do |form| %>
  <div class="col">
    <%= form.text_field :number,
                        placeholder: 'Number',
                        value: params.dig('filter', 'number'),
                        class: 'form-control' %>
  </div>

  <div class="col">
    <%= form.text_field :date,
                        placeholder: 'Date',
                        value: params.dig('filter', 'date'),
                        class: 'datepicker form-control' %>
  </div>

  <div class="col">
    <%= form.submit :filter, class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

app/views/internal/invoices/_form.html.erb
<%= form_with(model: invoice, url: internal_invoices_path, method: :post, local: true) do |form| %>
  <%= render 'layouts/errors', errors: invoice.errors %>

  <div class="mb-3">
    <%= form.label :number, class: 'form-label' %>
    <%= form.text_field :number, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.text_field :date, class: 'datepicker form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :company, class: 'form-label' %>
    <%= form.text_area :company, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :billing_for, class: 'form-label' %>
    <%= form.text_area :billing_for, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :total, class: 'form-label' %>
    <%= form.text_field :total, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :emails, class: 'form-label' %>
    <%= form.text_area :emails, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit :submit, class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

app/views/internal/invoices/edit.html.erb
<div class="container">
  <h1>Editing Invoice</h1>

  <div class="row">
    <%= render 'form', invoice: @invoice %>
  </div>

  <div class="row">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <%= link_to 'Show', internal_invoice_path(@invoice) %>
      </li>
      <li class="list-group-item">
        <%= link_to 'Back', internal_invoices_path %>
      </li>
    </ul>
  </div>
</div>

app/views/internal/invoices/index.html.erb
<div class="container">
  <h1>Invoices</h1>

  <div class="row">
    <%= render 'filters' %>
  </div>

  <div class="row">
    <table class="table">
      <thead>
      <tr>
        <th>Number</th>
        <th>Date</th>
        <th>Company</th>
        <th>Billing for</th>
        <th>Total</th>
        <th>Emails</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.number %></td>
          <td><%= invoice.date %></td>
          <td><%= invoice.company %></td>
          <td><%= invoice.billing_for %></td>
          <td><%= invoice.total %></td>
          <td><%= invoice.emails %></td>
          <td><%= link_to 'Show', internal_invoice_path(invoice), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_internal_invoice_path(invoice), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', internal_invoice_path(invoice),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: 'btn btn-primary' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <%= link_to 'New Invoice', new_internal_invoice_path %>
      </li>
    </ul>
  </div>
</div>

app/views/internal/invoices/new.html.erb
<div class="container">
  <h1>New Invoice</h1>

  <div class="row">
    <%= render 'form', invoice: @invoice %>
  </div>

  <div class="row">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <%= link_to 'Back', internal_invoices_path %>
      </li>
    </ul>
  </div>
</div>

app/views/internal/invoices/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-lg-4 order-md-last">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-primary">Invoice</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Number:</h6>
            <small class="text-muted"><%= @invoice.number %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Date:</h6>
            <small class="text-muted"><%= @invoice.date %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Company:</h6>
            <small class="text-muted"><%= @invoice.company %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Billing for:</h6>
            <small class="text-muted"><%= @invoice.billing_for %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Total:</h6>
            <small class="text-muted"><%= @invoice.total %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">Emails:</h6>
            <small class="text-muted"><%= @invoice.splitted_emails.join("<br>") %></small>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <%= link_to 'Download', internal_invoice_path(@invoice, format: :pdf), target: '_blank' %>
      </li>
      <li class="list-group-item">
        <%= link_to 'Edit', edit_internal_invoice_path(@invoice) %>
      </li>
      <li class="list-group-item">
        <%= link_to 'Back', internal_invoices_path %>
      </li>
    </ul>
  </div>
</div>

app/views/internal/invoices/show.pdf.erb
<p>
  <strong>Number:</strong>
  <%= @invoice.number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Billing for:</strong>
  <%= @invoice.billing_for %>
</p>

<p>
  <strong>Total:</strong>
  <%= @invoice.total %>
</p>