config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resource :registrations, only: [:new, :create] do
    collection do
      get :confirm
      get :generate
    end
  end
  resource :sessions, only: [:new, :create, :destroy] do
    get '/', action: :create
    get '/token', as: :token, action: :token
  end

  namespace :api do
    get '/', to: 'api/api#root'

    resources :invoices do
      member do
        get :send_email
      end
    end

    match '*unmatched', to: 'api/api#not_found', via: :all
  end

  namespace :internal do
    resources :invoices
  end

  root 'application#root'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :logged_redirect_to, only: :root, if: :signed_in?
  helper_method :signed_in?, :current_user

  def signed_in?
    warden.authenticated?(:internal)
  end

  def current_user
    warden.user(:internal)
  end

  def authenticate!
    warden.authenticate!(scope: :internal, store: true)
  end

  def warden
    env['warden']
  end

  def env
    request.env
  end

  def root
  end

  private

  def logged_redirect_to
    redirect_to internal_invoices_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/root.html.erb
<div class="container ">
  <div class="row">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to 'Generate Token', new_registrations_path, class: 'btn btn-primary' %>
      <%= link_to 'Login via Token', new_sessions_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>